name: Build and Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Clear Build
        run: rm -rf dist

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build & npm run package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: .

      - name: Test
        env:
          GH_TOKEN: ${{ secrets.SECURITY_TOKEN }}
        run: npm test


