name: Build and Test

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Clear Build
        run: rm -rf dist

      - name: Verify 01
        run: |
          pwd
          ls

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Verify 02
        run: |
          pwd
          ls
          ls src

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

      - name: Test
        env:
          GH_TOKEN: ${{ secrets.SECURITY_TOKEN }}
        run: npm test


