name: Manual Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout Sources
        uses: actions/checkout@v2
        
      - name: Invoke Action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sarifReportDir: ./samples/java/basic
