name: Manual Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Checkout Sources
        uses: actions/checkout@v2
        
      - name: List files
        run: |
          ls -l
          ls -l ./samples
          ls -l ./samples/basic
          
      - name: Invoke Action
        uses: ./
        with:
          token: ${{ secrets.SECURITY_TOKEN }}
          sarifReportDir: ./samples/java/basic
